### ISSUE TITLE
UNI value is equal to zero

### ISSUE THREAD

**Issue by 0xEval** [Eloise1988/COINGECKO#10]
This is perhaps due to Uniswap V3 release and Coingecko attempted support for V3 pools.

`=GECKOPRICE(B15,"USD")` where `B15 = "UNI"` will show a value equal to `0`

This worked fine yesterday?

**Comment by Eloise1988** [comment]
Changed the code. Latest version CoingeckoV2.gs available here:
https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs

<img width="581" alt="Screen Shot 2021-05-06 at 15 40 43" src="https://user-images.githubusercontent.com/53000607/117308103-7d3b8900-ae81-11eb-85ff-45ba7e11c28b.png">
