### ISSUE TITLE
Refactored GeckoPrice Function can't load within Google Custom Function timeout

### ISSUE THREAD

**Issue by btkircher** [Eloise1988/COINGECKO#11]
Really appreciate your work

Since implementing your V2 changes, the GeckoPrice API call no longer executes before the timeout limit set by Google. After reviewing your Sample Google Sheet, it appears this is happening on your side as well, but let me know if you need any additional data.

**Comment by Eloise1988** [comment]
Hi, 
Thank you for your message. Yes my sheets have been struggling but I haven't understood why?
Are you saying I need to increase the timeout value?
Thanks for your help,

**Comment by btkircher** [comment]
I suppose if it's on the server side with Goin Gecko's API there may not be much you can do. If I can find some time this week, I'll test making some API calls to Goin Gecko and focusing on the response times to confirm if that's the issue. At first, I thought the changes in V2 caused the performance drop, but I rolled back to V1 and it's also not loading data in time.

**Comment by pldelattre** [comment]
A likely explanation of the timeout : 
https://github.com/Eloise1988/COINGECKO/issues/5#issuecomment-840102981
