### ISSUE TITLE
Error with cache - Exception: Argument too large: key

### ISSUE THREAD

**Issue by pldelattre** [Eloise1988/COINGECKO#13]
Just wanted to let you know that the cache is crashing the code when custom functions are called with a long list of tickers. 

When you call 
`GECKOPRICE(ticker_array,defaultVersusCoin)` 
with a big ticker_array, that will result in big cache key because of 
`var id_cache=coinList+versusCoinList+'price'`
and then 
`var cached = cache.get(id_cache);`
will fail because the cache key is limited to 250 characters as explained here:
https://developers.google.com/apps-script/reference/cache/cache#put(String,String)

Possibles fixes : 
- Remove the cache 
- Hash the cache key

**Comment by Eloise1988** [comment]
Thank you!

Sorry for the late response. Yes I did implement the cash solution you proposed!
