### ISSUE TITLE
Do I need other scripts?

### ISSUE THREAD

**Issue by jdx-john** [Eloise1988/COINGECKO#14]
I've found a bit of a confusing mixture of crypto/gecko files online and I'm unclear, do I just need coingecko.gs or do I also need CryptoTools.gs, I was initially reading this page: https://medium.com/coinmonks/how-to-value-your-stocks-crypto-portfolio-in-google-sheets-22bb7b42c39d

**Comment by Tippon** [comment]
> I've found a bit of a confusing mixture of crypto/gecko files online and I'm unclear, do I just need coingecko.gs or do I also need CryptoTools.gs, I was initially reading this page: https://medium.com/coinmonks/how-to-value-your-stocks-crypto-portfolio-in-google-sheets-22bb7b42c39d

I started with this article from Eloise:

https://medium.com/the-cryptocurious/google-sheet-open-source-cryptotools-set-up-9420e3940a8a

Be aware though that Eloise is working on the code at the moment. The Telegram link is here:

https://t.me/TheCryptoCurious

**Comment by Eloise1988** [comment]
> I've found a bit of a confusing mixture of crypto/gecko files online and I'm unclear, do I just need coingecko.gs or do I also need CryptoTools.gs, I was initially reading this page: https://medium.com/coinmonks/how-to-value-your-stocks-crypto-portfolio-in-google-sheets-22bb7b42c39d

Some people only want functions related to Coingecko sothis is why I made 2 files. For all values for Coingecko (prices, volumes, marketcap etc...)
Coingecko code:
[https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs](https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs)

 But if you wish to have access to balances from blockchain addresses, staking, rewards, lending rates, dex volumes, dex prices etc... You need to include as well the CryptoTools code:
[https://raw.githubusercontent.com/Eloise1988/CRYPTOBALANCE/master/CRYPTOTOOLS_V2.gs](https://raw.githubusercontent.com/Eloise1988/CRYPTOBALANCE/master/CRYPTOTOOLS_V2.gs)

Like @Tippon said, don't hesitate to join the telegram channel for more information,
 [https://t.me/TheCryptoCurious](https://t.me/TheCryptoCurious)

**Comment by jdx-john** [comment]
Thanks @Eloise1988 so they are separate, not dependent on each other. I think I'm on the original version, I saw there was a V2 script file but not sure if that's still in development?

I don't know what Telegram is but this all seems to be working for me - thanks for your work!

**Comment by Eloise1988** [comment]
If you're happy with v1 stay on it.
 
V2 has been created to improve the performance of the functions because in V1, many users were hitting daily limits from Google.
V2 is still in beta mode.
