### ISSUE TITLE
GECKOPRICE does not return the price of some coins

### ISSUE THREAD

**Issue by lesstalkmoredrums** [Eloise1988/COINGECKO#19]
Hi and thanks for this great project!

For some COINS the return value of this functions is empty:

- geckoprice
- gecko24hpricechange
- geckoath

I have tried with these coins: PLANETS, SECO, TULIP, SLIM, SX
![image](https://user-images.githubusercontent.com/78214247/125658224-a9eb2705-88e5-4715-a5a1-9873617b0e7f.png)

**Comment by Eloise1988** [comment]
Hi,

Thanks! 
Yes some of the tickers don't return prices, it usually means that the script didn't find the Coingecko ID related to the ticker. 
You need to use the GECKO ID found here: https://api.coingecko.com/api/v3/search?locale=fr&img_path_only=1

In the case of 
TULIP -> solfarm
SECO -> serum-ecosystem-token
etc...

I also created the GECKOPRICEBYNAME() FUNCTION. It's explained in the following medium. 

Syntax: GECKOPRICEBYNAME(id_coin, currency)
1st parameter: the id name of cryptocurrency ticker found in web address of Coingecko 2nd parameter: the fiat currency ex: USD, EUR, GPB etc… 3rd parameter an optional fixed cell for automatic refresh of the data, this parameter
The id_coin of cryptocurrency ticker can be found in CoinGecko’s web address as shown on the above pictures. If the web address id is not functioning please refer to the id of your project found [here](https://api.coingecko.com/api/v3/search?locale=fr&img_path_only=1).


![GECKOPRICEBYNAME](https://user-images.githubusercontent.com/53000607/126041493-787fa67a-8f79-43e4-8229-1b432eb251c5.gif)


Hope this helps,
https://medium.com/the-cryptocurious/coingecko-prices-volumes-market-caps-in-google-sheets-and-excel-a1a3ee201cb8
![image](https://user-images.githubusercontent.com/53000607/126041417-81df0ef4-87c4-4ce2-a91f-9870ba270106.png)

**Comment by lesstalkmoredrums** [comment]
Thank you! It works perfectly!
