### ISSUE TITLE
How to install it in Google Sheet?

### ISSUE THREAD

**Issue by winzou** [Eloise1988/COINGECKO#2]
Hello,

I'm confused about how to copy/paste the content of `CoinGecko.gs`.
I've tried to paste it in the "Script Editor" of my spreadsheet, but it does not compile and outputs some errors.

Thanks for your insights

**Comment by Eloise1988** [comment]
Check if you have authorized Google Services 
Apps Script requires user authorization to access private data from built-in Google services or advanced Google services.
![autho1](https://user-images.githubusercontent.com/53000607/106246575-a0b1c080-620e-11eb-9903-33538a56ca25.png)
![autho2](https://user-images.githubusercontent.com/53000607/106246583-a1e2ed80-620e-11eb-99bc-e981dabe6e41.png)
![autho3](https://user-images.githubusercontent.com/53000607/106246581-a1e2ed80-620e-11eb-942b-47d2cdf35b74.png)
![autho5](https://user-images.githubusercontent.com/53000607/106246576-a0b1c080-620e-11eb-9ba7-e38a4e7cbe2c.png)
![auth04](https://user-images.githubusercontent.com/53000607/106246578-a14a5700-620e-11eb-9026-389fb51e8ace.png)

**Comment by winzou** [comment]
Thanks for your anwser. I managed to make it work by removing all `await` and `async` keywords from the code. Was it supposed to work with these keywords? Weird.

**Comment by Eloise1988** [comment]
Strange.
It works also without await and async but it will give more errors.
If you want to see how a template of the CoinGecko works you can duplicate this one and check the code:
https://docs.google.com/spreadsheets/d/1QODede4loYFnd9ig_f4vRiO4J4uptxn8zIx3qRsLDeA/edit?usp=sharing

I've explained the CoinGecko functionalities in the following medium:
https://medium.com/the-cryptocurious/coingecko-prices-volumes-market-caps-in-google-sheets-and-excel-a1a3ee201cb8

**Comment by CueCueWhee** [comment]
I am facing issues with async also. I ported your code fully over, and syntax error still get throw out.
