### ISSUE TITLE
Clasp version of scripts

### ISSUE THREAD

**Issue by mabraithwaite** [Eloise1988/COINGECKO#20]
This isn't really an issue, but if you're interested, I made a repo with some changes to your functions and implemented clasp so you can deploy locally: https://github.com/mabraithwaite/crypto-scripts

**Comment by Eloise1988** [comment]
Great initiative,
Thank you so much, the code seems so neat!! 
I'll test it out soon!

**Comment by mabraithwaite** [comment]
Made a template portfolio too if you want to check it out (link in the readme)
