### ISSUE TITLE
Returning '0' when no market cap is found

### ISSUE THREAD

**Issue by 300Gram** [Eloise1988/COINGECKO#28]
Hi, 

I am having trouble to get the script to return '0' if no market cap is found. 
The reason of doing this is because I am doing some research analysis calculation using the market cap data to determine whether if it's a High cap Project. 

How can i do that? I tried doing `return pairList.map((pair) => pair[0] && (dict[pair[0]] && (dict[pair[0]] || "") || (defaultValueForMissingData !== null ? defaultValueForMissingData : "0")) || "0");` 

But no luck on it. Not very familiar with programming, so perhaps someone can help me out ?

**Comment by Eloise1988** [comment]
![image](https://user-images.githubusercontent.com/53000607/145825106-9d855838-45e4-48d5-ba4a-03f345652f37.png)
Hi,

I think you must replace "0" with 0
return pairList.map((pair) => pair[0] && (dict[pair[0]] && (dict[pair[0]] || "") || (defaultValueForMissingData !== null ? defaultValueForMissingData : 0)) || 0);

Hope that helps

**Comment by 300Gram** [comment]
Hi. 

Thank you for the speedy response! I have attempt to replace the code just like the screenshot you gave, but still instead of displaying 0 in the cell, it's displaying a blank cell.

**Comment by 300Gram** [comment]
Hi, Thank you! It's working. God programming so tough. Thank you very much!
