### ISSUE TITLE
Cannot read property 'toUpperCase'

### ISSUE THREAD

**Issue by muchobrento** [Eloise1988/COINGECKO#3]
TypeError: Cannot read property 'toUpperCase' of undefined
GECKOPRICE	@ CoinGecko.gs.gs:51
<img width="1008" alt="Screen Shot 2021-02-10 at 10 42 01 AM" src="https://user-images.githubusercontent.com/6628770/107549235-d058b500-6b8c-11eb-9efa-7e9649497ab3.png">

**Comment by Eloise1988** [comment]
I'm not sure where the issue comes from.
Here is a public template sheet with the embed CoinGecko.gs code. 
If you duplicate, it should work fine.

https://docs.google.com/spreadsheets/d/1QODede4loYFnd9ig_f4vRiO4J4uptxn8zIx3qRsLDeA/edit?usp=sharing

**Comment by d3dawizard** [comment]
Same issue no luck. The pull gets hung up in "Error Loading Data..."

**Comment by devinmancuso** [comment]
+1 same issue here.

**Comment by d3dawizard** [comment]
I think I know what MY issue was, maybe it is similar. I just had too many pull requests from google. I left my google sheets up and went to bed. It timed everything out for 24h, gave it a break and it worked. I have since moved on, but I really liked this idea.

**Comment by Eloise1988** [comment]
Issue seems to come from the localization of Sheet. 

Depending on the country, formulas are written differently. 

In **File Spreadsheet setting, check that Locale** is set as United States
![photo_2021-04-15 09 19 39](https://user-images.githubusercontent.com/53000607/114829745-bd9c6f80-9dcb-11eb-8daf-2547ef5b6130.jpeg)

If it's not you can, for example for France, you would call formula using a semi-colon instead of a comma.
Let's say you want Bitcoin's price:

When locale is set to **United States** formula is:
=GECKOPRICE("BTC"**,**"USD")

When locale is set to **FRANCE** formula is:
=GECKOPRICE("BTC"**;**"USD")

**Comment by joaojorgem** [comment]
Im having the same problem. 
![image](https://user-images.githubusercontent.com/61193885/115237469-818f4480-a114-11eb-8dbb-d8c977d031cb.png)
I changed my spreadsheet time and local to United Stated but it still doesnt read the "toUpperCase" method

**Comment by Eloise1988** [comment]
Did you try the 2 formulas one with comma and the other one with semi colon:
When formula is, what do you get ?
=GECKOPRICE("BTC","USD")

When formula is, what do you get ?
=GECKOPRICE("BTC";"USD")

FYI: you can reach me here:
https://t.me/TheCryptoCurious
It's easier to trouble shoot.

**Comment by joaojorgem** [comment]
I figured it out
First I fixed the local and time zone for these settings:
[image: image.png]
Then I used the formula : =GECKOPRICE("BTC","USD")

And

Em seg., 19 de abr. de 2021 às 13:58, Eloisa ***@***.***>
escreveu:

**Comment by joaojorgem** [comment]
I figured it out.
First I changed the spreadsheet settings to the following one in the
image attached (Even though I'm in Ireland atm);
Then I used the function :   " =GECKOPRICE("XXX", "USD") "   on my
spreadsheet column .
Sometimes this function doesn't work properly so I used :      "
=GECKOPRICE("XXX", "USD" ,$A$1)"

When I execute the script it still doesn't  work. It gives me an error
message on the line 50, for the "toUpperCase" method. But the function
works fine on the spreadsheet.
- The code has to be implemented and saved  and allowed on the Script
editor, it doesn't need to run .
- The local and time zone has to be changed to the United States.
- The functions above have to be written exactly the way they are
(besides de XXX of course which is the token acronym).




Em seg., 19 de abr. de 2021 às 13:58, Eloisa
***@***.***> escreveu:

**Comment by sbdonslaught** [comment]
Hello, 

I'm getting the same issue as stated above.

I have the spreadsheet settings to be in the United States. I've tried copying the spreadsheet you linked above as well, I get the same error when debugging the code on that sheet too.

Has there been any fix for this?

**Comment by Eloise1988** [comment]
Hello,

Thank you for letting me know. I changed the settings of the sheets. It should work now when you make a copy of the following sheet:https://docs.google.com/spreadsheets/d/1QODede4loYFnd9ig_f4vRiO4J4uptxn8zIx3qRsLDeA/edit?usp=sharing

**Comment by sbdonslaught** [comment]
I don't know why but I'm still getting this issue. :/

I've duplicated the sheet, tested it on my own, ran the debug, and it's still not liking the toUpperCase and toLowerCase function.

I'm not sure what other troubleshooting I can do. Any advice?

**Comment by joaojorgem** [comment]
The code doesnt need to run properly to have the function GECKOPRICE
working on ur google sheet.
Ignore that toUpperCase method

**Comment by Eloise1988** [comment]
What is the message you get when entering your formula in Google Sheets? Can you print screen your formula?

**Comment by sbdonslaught** [comment]
I don't know what changed, but I made a third copy of the spreadsheet linked above and it seems to be working now.

Thank you for the quick responses, I really appreciate the help and the scripts! :)
