### ISSUE TITLE
Got #NUM error in Google Sheets

### ISSUE THREAD

**Issue by SzilagyiR** [Eloise1988/COINGECKO#30]
Hi!

I trying to use GECKOCHART, it works fine, but when I refresh it to update, I gave an error message #NUM. (The result is not a number.)

If I change something, like days, it works again until I refresh it.

**Comment by fabform** [comment]
This is handy to find google sheets id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by Eloise1988** [comment]
@SzilagyiR 

It's hard for me to say but I think you might be hitting  the coingecko limits if see an error 429 directly in app script. 
![telegram-cloud-photo-size-4-5809683703478203519-y](https://user-images.githubusercontent.com/53000607/148640074-096477bd-58f5-49c7-a3e4-ef1c8b0fe6a0.jpg)

CoinGecko decreased their limits to 50 api calls/min by IP address. When using Google we are all using the same IP addresses, they do not differentiate per user account. Even if you are not requesting 50 calls a minute someone else using sheets that is on the same IP address as yours might be using them. As a result you get blocked until the next minute.
