### ISSUE TITLE
Error using GECKOHIST function

### ISSUE THREAD

**Issue by wai-l** [Eloise1988/COINGECKO#35]
Hi there :)
I have copied the script of [CoinGeckoV2.gs](https://github.com/Eloise1988/COINGECKO/blob/master/CoinGeckoV2.gs) and tried to use it on my own Google Sheets, but keep on getting ERROR tried to use the GECKOHIST function.
(I tried other functions like GECKOPRICE and GECKOVOLUME and they worked fine.)
May I know what the issue would be?

I tried
`=GECKOHIST("BTC", "usd", "Volume", "02-02-2022", "09-11-2021")`
which returns Error.

and I also tried 
`=GECKOHIST("ethereum","usd","price",datevalue("12-31-2020"),datevalue("08-31-2020"))`
which I saw you posted on another Issues post a while ago.
It returns #ERROR! with the following statement: 

>  Exception: Request failed for https://api.coingecko.com returned code 429. Truncated server response: error code: 1015 (use muteHttpExceptions option to examine full response) (line 1013).

<img width="717" alt="Screenshot 2022-02-07 at 12 29 13" src="https://user-images.githubusercontent.com/96261784/152788285-c7bbd48b-4625-43e7-8d44-e2958e8bd2f9.png">

**Comment by Eloise1988** [comment]
Hi,

Code 429 is a limit issue not formula/code issue:
https://support.coingecko.com/help/why-am-i-getting-errors-with-a-status-code-429

In google sheets we are all using the same IP addresses so if someone else is requesting many calls at the same time, you will both exceed the limit together.

I already raised the issue with Coingecko but they are not willing to create specific free api keys right now.

**Comment by to-waiting-room** [comment]
Thank you for your reply :)
In that case I guess the only solution at this point would be to write my own scripts if I know how to?

**Comment by Eloise1988** [comment]
In fact, the only solution is not to use the Google sheet but have your own servers that do computations for you and then sends the info to your Google Sheet.

**Comment by to-waiting-room** [comment]
Oh I see what you mean now, seems way over my skills level but at least I can give up trying now LOL
Cheers :)
