### ISSUE TITLE
Any way to get the ATH Date

### ISSUE THREAD

**Issue by MR-T77** [Eloise1988/COINGECKO#36]
Is there any way to get the ATH date?

**Comment by Eloise1988** [comment]
Example:
=GECKO_ID_DATA("btc","market_data/ath_date/usd")
![image](https://user-images.githubusercontent.com/53000607/156347335-dc67cf95-e61f-42b1-b9cc-a920d77ed259.png)

**Comment by MR-T77** [comment]
Thanks

**Comment by MR-T77** [comment]
I'm getting an error: "ReferenceError: id_cache is not defined (line 986).", for the VRA (verasity) case. Any idea why?

**Comment by Eloise1988** [comment]
There was a bug in the code, I fixed it.
Refresh your code with the following:
https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs

Let me know if you are still encountering issues.

**Comment by MR-T77** [comment]
Now I made a refresh and everything's still loading...it seems I broke the daily limit
