### ISSUE TITLE
CoinGeckoV2.gs does not save/compile as is, in new Google App Scripts file

### ISSUE THREAD

**Issue by aaronmboyd** [Eloise1988/COINGECKO#38]
`CoinGeckoV2.gs` commit `2a4cc71d027b1a6f00aee52848c734cccbc5bc37` does not save in a new file in Google App script, fails with syntax error (my file is named gecko.gs):
```
Missing ; before statement. (line 91, file "gecko")
```
If I delete the `async` keyword from all functions the error line moves around (to line 104) but the error remains. Neither line 91 or 104 appear to by missing semicolons and are otherwise complete.

Tried in both the old and new App Scripts setup.

**Comment by Eloise1988** [comment]
Hi @aaronmboyd 

I made a video that shows how to load the script.
https://www.youtube.com/watch?v=___BlVNV1T8

Let me know if you still encounter issues.

**Comment by aaronmboyd** [comment]
@Eloise1988 I've figured it out. You need to have the Chrome V8 Runtime setting enabled. (I was importing into an existing project with this setting turned off).

![image](https://user-images.githubusercontent.com/13218496/190634246-f267f70d-c950-442b-b800-fb4f7a8bd78c.png)

**Comment by Eloise1988** [comment]
Thanks for letting me know about that issue.
