### ISSUE TITLE
a way to differentiate coingecko max limits and empty data

### ISSUE THREAD

**Issue by alexis26** [Eloise1988/COINGECKO#39]
Hi,

with coingecko2.1, in comparison to V1, I have a problem with the situation of empty cells...

indeed with V2, as seen and discussed on telegram, we sometimes have an empty cell response when we reached the limit of daily requests for the free version of the coingecko api.

this is a problem for me for some data for which there is a "null" answer from the API, meaning "no-data"; that we cannot distinguish from this daily limit...

(so for some data I still use the old v1 version, because it always returns '#error' when the limit is reached; so it's the only way I found to distinguish these 2 states...)

So, if one day you have to touch up this script, it would be great to add a piece of code to distinguish these 2 things/states...

Anyway, a big MERCI for all your work on this script and the API... :heart_eyes:
Alexis

**Comment by Eloise1988** [comment]
Hi Alex,

Do you see this error on a specific function?

**Comment by alexis26** [comment]
Hi,

I have the impression that it is almost for all the functions...
when you have reached the daily limit of the coingecko api (free version)...

when you call the "direct" function '=GECKOXXXX(...)' and the limit of the requests is reached the cell remains (often) empty; where with v1 we had, we have, always "#error"
(I will note when this specific case occurs and will come back to you here, to know exactly which functions...)

Of course, there is the message of google-sheet 'in comment of the cell' : 'Exceeded maximum execution', but only when your formula is "in direct"...
if it is "indirect", eg: '=IF(A1="";"";GECKOXXXX(...))', you don't even have this message and the cell remains empty...
So, it prevents to use formulas like 'IFERROR(A1, "xxxxxxxxxx")'.

Most of the time this is not a problem because we know that, normally, there should be data in an empty cell (so we can adapt our formulas)...

...But when we are in the case of data that can be 'null' it is a problem because we can't distinguish the limit reached with an empty data...
ex: "market_data/total_value_locked" or "market_data/mcap_to_tvl_ratio "or "market_data/fdv_to_tvl_ratio

Alexis
