### ISSUE TITLE
Issue with some ticker on Coingecko

### ISSUE THREAD

**Issue by Flow40** [Eloise1988/COINGECKO#4]
Hi Eloise,

Thanks for the share, its a very usefull script. However, I am really new in programming and cannot understand everything.

There is an issue, some of the tickers are the same for different crypto on coingecko such as MDS corresponding to medishare and mdsquare, or NODE for pocket node and whole network.
I was thinking to add a condition to allow the user to enter either the symbole (MDS) or the id (medishare) but I am not sure how to do it, and if it will be applicable to the script.

Cheers,
Flow

**Comment by Eloise1988** [comment]
Hi Flow,

For coins that have similar tickers, you need to use the GECKOPRICEBYNAME function and find the id [here](https://api.coingecko.com/api/v3/search?locale=fr&img_path_only=1) corresponding to the correct project.

For example mdsquare:
The id is mdsquare
function is then =geckopricebyname("mdsquare","usd")

For more information on the geckopricebyname function [here](https://medium.com/the-cryptocurious/coingecko-prices-volumes-market-caps-in-google-sheets-and-excel-a1a3ee201cb8)
