### ISSUE TITLE
about the March 2023 update annotation 

### ISSUE THREAD

**Issue by alexis26** [Eloise1988/COINGECKO#40]
Hi,

about the switch from "https://api.coingecko.com/api/v3/search?locale=fr&img_path_only=1"
to "https://api.coingecko.com/api/v3/coins/list

there is still a reference to it for GECKOCHANGE (l.1372) and GECKOLOGO (l.1524)...

Is it important, should it be changed? or can it be left as it is?

(if I change) Is it enough to change that :
".coingecko.com/api/v3/search?locale=fr&img_path_only=1"
--> ".coingecko.com/api/v3/coins/"
or are there other modifications/changes to be done on the code of these parts?

thank you

**Comment by Eloise1988** [comment]
Hi Alexis,

Thank you for bringing this to my attention. You are right, there are still references to the old API endpoint for GECKOCHANGE and GECKOLOGO. I have corrected this in the [new version](https://github.com/Eloise1988/COINGECKO/blob/master/CoinGeckoV2.gs) of the code by replacing ".coingecko.com/api/v3/search?locale=fr&img_path_only=1" with ".coingecko.com/api/v3/coins/".

This change should be sufficient and there are no other modifications/changes needed for these parts of the code.

Thanks again for pointing this out and let me know if you have any other questions or concerns.

Best regards,
Eloise

**Comment by alexis26** [comment]
You're welcome, it's mainly me who owes you a big 'thank you' for all the work you share ... :-)))
