### ISSUE TITLE
PEPE Price is not fetched correctly

### ISSUE THREAD

**Issue by ismailberkan** [Eloise1988/COINGECKO#45]
Hi,

I was trying CoinGecko API script through Google Sheets and PEPE coin price was shown wrong. The PEPE price as of writing this is about 0.00002007 but on Google Sheet is shown as 0.00005021 (fixed price). Please see the attached screenshot.
 
I used the following function to call the PEPE price:
=GECKOPRICE("pepe")

Am I missing something here?

Thank you.
<img width="279" alt="Screenshot 2024-11-18 at 20 10 39" src="https://github.com/user-attachments/assets/cdc2e1c5-3d86-4083-803e-aa362ee203da">

**Comment by ismailberkan** [comment]
Hi, I am just following up if you had a chance to look at my query above. Many thanks.

**Comment by Eloise1988** [comment]
=GECKOPRICEBYNAME("pepe")

**Comment by ismailberkan** [comment]
Thank you so much.
