### ISSUE TITLE
All calls are failing (even in sample public sheet)

### ISSUE THREAD

**Issue by nhmtns** [Eloise1988/COINGECKO#5]
Eloise - Thank you so much for your much useful work and sharing! 

These calls are succeeding sometimes (once or twice in the day) but most of the time they are failing and giving #ERRROR as the result with reason - "Exceeded Maximum Execution time line(0)"

I made a copy of your sample CoinGecko spread sheet and reproduced the same issue in that file also..

Obviously this seem like a network issue and calls are timing out. However, I confirm my network is fine and I am able to access internet just fine while these failures are happening. 

Thanks

**Comment by nhmtns** [comment]
Further, looked at the execution log, and all function calls are exceeding 30.0 sec and thus failing.. Apparently custom functions have 30s time limit..

**Comment by Eloise1988** [comment]
I believe you are hitting your Google API quotas
The limits are as[ follows](https://developers.google.com/apps-script/guides/services/quotas)
<img width="912" alt="Screen Shot 2021-03-06 at 14 44 31" src="https://user-images.githubusercontent.com/53000607/110209047-a6906680-7e8a-11eb-99fa-2cacf9d4d0fa.png">

**Comment by phouverneyuff** [comment]
Why when there is an error, you return calling the same function on GECKOPRICE function?
If an error occurs, you will exceed your quota. 
I started to receive this message: "Exception: Service invoked too many times for one day: urlfetch."

I suggest changing from:

`  catch(err){
    return GECKOPRICE(ticker,currency);
  }`

to:

`
  catch(err){
    Logger.log(err);
  }
`

Or maybe try implement a max retry limit fetch API.

**Comment by phouverneyuff** [comment]
I also started to use cache on ids

```
async function GECKOPRICE(ticker,currency){
  Logger.log("GECKOPRICE")
  Utilities.sleep(Math.random() * 100)
  ticker=ticker.toUpperCase()
  currency=currency.toLowerCase()
  id_cache=ticker+currency+'price'
  var cache = CacheService.getScriptCache();
  var cached = cache.get(id_cache);
  if (cached != null) {
    Logger.log("coin " + ticker + " price cache hitted")  
    return Number(cached);
  }
  
  try{

    var coinIDCache = ticker+'id'
    var coinIdCached = cache.get(coinIDCache)
    var id_coin = null

    if (coinIdCached == null) {
      url="https://api.coingecko.com/api/v3/search?locale=fr&img_path_only=1"
      Logger.log("url " + url)
      var res = await UrlFetchApp.fetch(url);
      var content = res.getContentText();
      var parsedJSON = JSON.parse(content);
      var coinsIds = parsedJSON.coins;
      Logger.log("coins ids getted")
      
      for (var i=0;i<coinsIds.length;i++) {
        cache.put(coinsIds[i].symbol+'id', String(coinsIds[i].id.toString()));
        if (coinsIds[i].symbol==ticker)
        {
          id_coin=coinsIds[i].id.toString();
          break;
        }
      }
    } else {
      Logger.log("coin " + ticker + " id cached hitted")
      id_coin = String(coinIdCached)
    }
        
    Logger.log("id_coin: " + id_coin )    
    
    url="https://api.coingecko.com/api/v3/simple/price?ids="+id_coin+"&vs_currencies="+currency;
    
    var res = UrlFetchApp.fetch(url);
    var content = res.getContentText();
    var parsedJSON = JSON.parse(content);
    
    price_gecko=parseFloat(parsedJSON[id_coin][currency]);
    cache.put(id_cache, Number(price_gecko));

    Logger.log("price_gecko: " + price_gecko)
    
    return Number(price_gecko);
  }
  
  catch(err){
    Logger.log(err);
    return err
    //return GECKOPRICE(ticker,currency);
  }
```

**Comment by Eloise1988** [comment]
Hi,

Thank you for your message.

I used to have it logging the error but users complained of all the errors that were appearing. 

The errors didn't come from a wrong input but from Google failing to receive a urlfetch response in time.

So let's say on 20 calls, 10 would appear but the other 10 had to be manually refreshed. So instead of logging the error, I recalled the function which would load the 20 calls correctly. 

I understand your point of exceeding the API limit much quicker but for most users, they prefer it that way than having to manually refresh the cells that didn't receive a response in time.

Thanks for the coinIdCached, it's a good idea. I'll implement it in the code.

**Comment by pldelattre** [comment]
I'm facing this issue too and when you log the error, you can see that the Coingecko API is answering with an error code : 429.

A likely reason can be found in : 
https://www.coingecko.com/en/api_terms
> Rate limit for the CoinGecko API is 10 calls each second per Internet Protocol (“IP”) address

We likely share the same pool of IP addresses from Google’s servers for calls from Google Sheet.
So the more users, the more errors we will be facing :(

**Comment by Eloise1988** [comment]
There was a problem with the caching of the Geckoprice function. 
I hashed the cache to make sure it's length does not exceed 250 characters.

I've updated the code. It can be found here:
[https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs](https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs)

Template sheet:
[https://docs.google.com/spreadsheets/d/1QODede4loYFnd9ig_f4vRiO4J4uptxn8zIx3qRsLDeA/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1QODede4loYFnd9ig_f4vRiO4J4uptxn8zIx3qRsLDeA/edit?usp=sharing)
